### ISSUE TITLE
LocalDate is Invalid

### ISSUE THREAD

**Issue by devstar0209** [Cybrid-app/cybrid-api-bank-kotlin#1]
When I try to create a customer, I keep getting like date_of_birth is invalid, date_of_birth must not be empty.
Let me share my code.
val postCustomerBankModel = PostCustomerBankModel(
                                    PostCustomerBankModel.Type.individual,
                                    PostCustomerNameBankModel(firstName, lastName),
                                    PostCustomerAddressBankModel(street, city, country, null, state, postalCode),
                                    LocalDate.parse(dob, DateTimeFormatter.ofPattern("yyyy/MM/dd", Locale.US)),
                                    null,
                                    auth.currentUser!!.email,
                                    listOf(PostIdentificationNumberBankModel(PostIdentificationNumberBankModel.Type.driversLicense, "US", idNumber))
                                )

How can I format for LocalDate?
Please help me to solve it.
Regards.

**Comment by michael-cybrid** [comment]
Hi @gitdevstar, I'm having trouble reproducing this. Can you share the serialized request that is being sent?

**Comment by michael-cybrid** [comment]
Closing as stale.
